# Welcome to Jekyll!

# Website settings
title: "Naveed Ahmed Usmani"
description: "Naveed Ahmed Usmani's landing page."
keywords: "Naveed,Naveed Usmani,Naveed Ahmed Usmani,resume,landing page,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://naveedhd.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Naveed'
  first_name: 'Ahmed Usmani'
  last_name: 'Naveed'
  email: 'naveedhd@gmail.com'
  linked_url: 'https://kr.linkedin.com/in/naveedusmani'
  facebook_username: 'naveedhd'
  github_username: 'naveedhd'
  head_img: 'static/img/landing/Naveed.jpg'
  desc: 'I am a Software Engineer currently in Seoul helping autonomous mobile robots deliver goods. My interest lies in Robotics and background in Electronics and Control Engineering. Looking to sharpen my skills in Software Engineering and broadening my skill set and experience.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

  - id: 'career'
    i18n: 'nav.career'
    name: 'Career'
    tpl: 'career.html'
    css: 'timeline'

  - id: 'skills'
    i18n: 'nav.skills'
    name: 'Skills'
    tpl: 'skills.html'
    css: 'team'

  # - id: 'projects'
  #   i18n: 'nav.projects'
  #   name: 'Projects'
  #   tpl: 'projects.html'
  #   css: 'project'

  - id: 'links'
    i18n: 'nav.link'
    name: 'Links'
    tpl: 'links.html'
    css: 'contact'

# google analytics
# ga:
#   id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
